"""
Lesson Schema — Pydantic models for AI-generated lesson plans.
The AI outputs structured JSON that validates against these models.

The 8-Step Pedagogical Structure:
  1. Hook / Curiosity
  2. Ultra Simple Intuition
  3. Visual Understanding
  4. Formal Definition
  5. Formula Introduction
  6. Multiple Examples
  7. Advanced Intuition (edge cases, misconceptions)
  8. JEE Advanced Level Understanding
"""

from __future__ import annotations
from pydantic import BaseModel, Field
from typing import Optional
from enum import Enum


class DifficultyLevel(str, Enum):
    TODDLER = "toddler"
    SCHOOL = "school"
    JEE_MAIN = "jee_main"
    JEE_ADVANCED = "jee_advanced"
    OLYMPIAD = "olympiad"


class ExplanationStyle(str, Enum):
    ANALOGY = "analogy"
    VISUAL = "visual"
    MATHEMATICAL = "mathematical"
    INTUITIVE = "intuitive"
    HISTORICAL = "historical"
    EXPERIMENTAL = "experimental"
    REAL_WORLD = "real-world"
    STORYTELLING = "storytelling"


class FormulaBreakdown(BaseModel):
    """Detailed breakdown of a single formula."""
    latex: str = Field(..., description="The formula in LaTeX")
    plain_english: str = Field(default="", description="What this formula says in words")
    variable_meanings: dict[str, str] = Field(default_factory=dict, description="Variable -> meaning")
    why_it_works: str = Field(default="", description="Intuition behind the formula")
    unit_check: str = Field(default="", description="Dimensional analysis / unit interpretation")


class Example(BaseModel):
    """A single illustrative example within a subconcept."""
    title: str = Field(..., description="Short title of the example")
    description: str = Field(..., description="Full explanation text")
    difficulty: DifficultyLevel = DifficultyLevel.SCHOOL
    style: ExplanationStyle = ExplanationStyle.INTUITIVE


class SubConcept(BaseModel):
    """A single sub-topic within a larger lesson, following the 8-step pedagogy."""
    name: str = Field(..., description="Name of the subconcept")

    # Step 1: Hook
    hook: str = Field(
        default="",
        description="A surprising fact, question, or real-world scenario to spark curiosity"
    )

    # Step 2: Intuition
    intuition: str = Field(
        default="",
        description="Ultra-simple explanation using everyday analogies, zero jargon"
    )

    # Step 3: Visual description (guides the scene planner)
    visual_description: str = Field(
        default="",
        description="Detailed description of what the animation should show to teach this concept"
    )

    # Step 4: Formal definition
    formal_definition: str = Field(
        default="",
        description="Proper scientific/mathematical definition, introduced AFTER intuition"
    )

    # Step 5: Formulas
    formula_breakdowns: list[FormulaBreakdown] = Field(
        default_factory=list,
        description="Gradual formula introductions with variable meanings and intuition"
    )

    # Step 6: Examples (easy → moderate → advanced)
    examples: list[Example] = Field(default_factory=list)

    # Step 7: Advanced intuition
    advanced_intuition: str = Field(
        default="",
        description="Deeper insights, edge cases, common misconceptions, limiting cases"
    )

    # Step 8: JEE-level insights
    jee_level_insight: str = Field(
        default="",
        description="Advanced problem-solving patterns, conceptual linking, shortcuts"
    )

    # Legacy / compatibility fields
    explanation: str = Field(default="", description="Full narration text (legacy, still used by scene planner)")
    required_visuals: list[str] = Field(default_factory=list, description="Visual element tags needed")
    key_equations: list[str] = Field(default_factory=list, description="LaTeX equations if any")
    difficulty: DifficultyLevel = DifficultyLevel.SCHOOL
    duration_seconds: int = Field(default=60, ge=5, le=120)
    alternative_explanations: list[str] = Field(
        default_factory=list,
        description="Alternative ways to explain the same concept (different analogies)"
    )
    misconceptions: list[str] = Field(
        default_factory=list,
        description="Common student misconceptions to explicitly address"
    )


class QuizQuestion(BaseModel):
    """An interactive question to test understanding."""
    question: str
    options: list[str] = Field(default_factory=list)
    correct_answer: str
    explanation: str
    difficulty: DifficultyLevel = DifficultyLevel.SCHOOL


class LessonPlan(BaseModel):
    """
    Complete lesson plan generated by the AI.
    This is the top-level output of the LessonPlanner.
    """
    topic: str = Field(..., description="Main topic being taught")
    summary: str = Field(..., description="One-line hook summary for the student")
    difficulty_progression: list[DifficultyLevel] = Field(
        default_factory=lambda: [
            DifficultyLevel.TODDLER,
            DifficultyLevel.SCHOOL,
            DifficultyLevel.JEE_MAIN,
        ]
    )
    prerequisites: list[str] = Field(default_factory=list, description="Topics the student should know first")
    subconcepts: list[SubConcept] = Field(..., min_length=1)
    quiz_questions: list[QuizQuestion] = Field(default_factory=list)
    estimated_duration_minutes: int = Field(default=8, ge=1, le=60)
    teaching_notes: Optional[str] = Field(default=None, description="Internal notes for the teaching engine")
